### ISSUE TITLE
Add list of friends to user profile view

### ISSUE THREAD

**Issue by AndrewM131** [uchicago-cs/chigame#144] opened 2023-11-06 23:18 UTC
Summary:
When a user goes to their profile page, they can see a table of their friends' usernames. The goal of this issue is first to set up a table view of all of a user's friends so that in the future, new features can be implemented in this table, such as friend rankings for who has won the most number of tournaments, etc. If the user is an admin or the User instance does not have a corresponding UserProfile instance, then the friends table will not show up on the profile page.

**Comment by AndrewM131** [comment] 2023-11-06 23:38
Description: We want to implement a part of the profile view that allows users to see their list of friends.

**Comment by AndrewM131** [comment] 2023-11-14 20:03
Update: We created a PR and requested a review. After the first review, we'll need to make changes to the code, and re-request a review.

**Comment by henrietta-k** [comment] 2023-12-03 20:06
Update November 30: Fixed merge conflicts and changed the position of the if statement on user_detail.html so that the Friends table only shows up if the user has friends.

**Comment by henrietta-k** [comment] 2023-12-03 20:07
Update December 3: PR has been approved.

**Comment by henrietta-k** [comment] 2023-12-03 20:11
Closing statement: the issue is completed. When a user goes to their profile page, if the user is not logged in as an admin and they have a corresponding UserProfile, they are able to see a table of all their current friends. This feature will allow future features to be implemented, such as seeing which friend is most highly ranked, etc. All the assignees worked together to write the code for this but I was in charge of making the GitHub PR.

**Closed as completed by henrietta-k** 2023-12-03 20:11 UTC
Labels: x/user-profiles-friending

**Comment by elizabethli31** [comment] 2023-12-09 20:04
Issue Score: Excellent

Comments:
This issue took two sprints to complete since the PR wasn't closed until sprint 3. But I like that you explained the exact goals of what this issue was to accomplish and what that was to look like for different users.
